In [ ]:
#default=[1,2,3,4,5,6]
default=[2]

In [ ]:
import argparse
import configparser
import sys

from datetime import datetime

import torch

import conf
from db import InfluxDB, datetime_to_nanosec
from network import Network
from swat_dataset import SWaTDataset


#assert torch.cuda.device_count() >= 1

BATCH_SIZE = 4096

org = "Osaka"

DB = InfluxDB('swat',org)

#import influxdb_client
#from influxdb_client.client.write_api import SYNCHRONOUS

#bucket = "swat"
#org = "Osaka"
#token = "2g_Q50vP5zhuxKx-y8Z3YoMBlRJA7t-c1C9c446mtrF4uUULh1ikdYy7MIBgsiY3NsAbxM5JasJKkm3HbdINsA=="
# Store the URL of your InfluxDB instance
#url="http://localhost:8086"

#client = influxdb_client.InfluxDBClient(
#    url=url,
#    token=token,
#    org=org
#)

#write_api = client.write_api(write_options=SYNCHRONOUS)


#parser = argparse.ArgumentParser(description='Trainer')

#parser.add_argument('--gpu', type=int, help='GPU index for learning (1-6)')
#parser.add_argument('--save', type=int, help='The index of trained network')
#args = parser.parse_args()

#print(f'* target processes: {args.process}')
#print(f'* use CUDA with GPU #{args.gpu}')
#print(f'* N-programming index: #{args.save}')

config = configparser.ConfigParser()
config.read('config.ini')
training_conf = config['train']

for pidx in default:
    print(f'* starts to train process {pidx}')

    dataset = SWaTDataset('dat/normal-P{}.dat'.format(pidx))

    p_features = len(conf.P_SRCS[pidx - 1])
    print(f'* # of features: {p_features}')
    pnet = Network(pidx=pidx, gidx=1, n_features=p_features, n_hiddens=conf.N_HIDDEN_CELLS)

    influx_measurement = conf.TRAIN_LOSS_MEASUREMENT.format(pidx)
    print(influx_measurement)
    DB.clear(influx_measurement)

    training_start = datetime.now()
    epochs = int(training_conf['epochs'])
    print(f'* training is going to repeat {epochs:,} times (epochs)')
    pnet.train_mode()

    min_loss = sys.float_info.max
    train_losses = []
    for e in range(epochs):
        
        start = datetime.now()
        loss = pnet.train(dataset, BATCH_SIZE)
        print(f'printing loss {loss}')
        #train_losses.append(loss)
        #globals()[f'p{e}'] = influxdb_client.Point(influx_measurement).tag(" ", " ").field('train_loss_{}', loss)
        #write_api.write(bucket=bucket, org=org, record= globals()[f'p{e}'])
        
        #DB.write(
        #    influx_measurement,
        #    {},
        #    {'train_loss_{}'.format(1): [loss]},
        #    [datetime_to_nanosec(datetime.now())]
        #)
        print(f'train loss {train_losses}')
        saved = False
        if loss < min_loss:
            min_loss = loss
            pnet.save(1, min_loss)
            saved = True
        print(f'[{e+1:>4}] {loss:10.6} ({datetime.now() - start})' + (' -> saved' if saved else ''))
    print(f'* the total training time: {datetime.now() - training_start}')

In [ ]:
for i in range(0,len(train_losses)):
    print(train_losses[i])


In [ ]:
for i in range(10):
    globals()[f'p{i}']=i
    
print(p2)

In [ ]:
import matplotlib.pyplot as plt
ax = plt.figure().gca()

ax.plot(train_losses)
plt.ylabel('Loss')
plt.xlabel('Epoch')
plt.legend('train')
plt.title('Loss over training epochs')
plt.show();

In [ ]:
import argparse
import sys
from datetime import datetime

import torch
from torch.utils.data import ConcatDataset

import conf
from db import InfluxDB, datetime_to_nanosec
from network import Network
from swat_dataset import SWaTDataset

N_DUPLICATE_RUNS = 2

BATCH_SIZE = 1024  # larger validation batch is possible, but DB is the bottleneck
#DB = InfluxDB('swat')

#parser = argparse.ArgumentParser(description='validator')
#parser.add_argument('--process', type=int, help='Process index (1-6)')
#args = parser.parse_args()

#pidx = args.process
pidx = 1
assert 1 <= pidx <= 6
#DB.clear(conf.EVAL_MEASUREMENT.format(pidx))

p_features = len(conf.P_SRCS[pidx - 1])
pnet = Network(pidx=pidx, gidx=pidx, n_features=p_features, n_hiddens=conf.N_HIDDEN_CELLS)

current_min_loss = sys.float_info.max
min_idx = 1
#for i in range(N_DUPLICATE_RUNS):
    #min_loss = pnet.load(i + 1)
    #print(f'* loaded saved network #{i+1}, min_loss: {min_loss}')
    #if min_loss < current_min_loss:
        #min_idx = i + 1
        #current_min_loss = min_loss
print(f'* the minimum loss index: {min_idx}')
pnet.load(min_idx)

dataset = ConcatDataset(
    [SWaTDataset('dat/normal-P{}.dat'.format(pidx)),
     SWaTDataset('dat/attack-P{}.dat'.format(pidx))]
)

pnet.eval_mode()
start = datetime.now()
val_losses = []
with torch.no_grad():
    loss = pnet.eval(dataset, BATCH_SIZE, db_write=False)
#DB.write(conf.TRAIN_LOSS_MEASUREMENT.format(pidx), {}, {'val_loss': [loss]}, [datetime_to_nanosec(datetime.now())])
val_losses.append(loss)
print(f'* val loss: {loss} ({datetime.now() - start})')

In [ ]:
for i in range(0,len(val_losses)):
    print(val_losses[i])

In [ ]:
import argparse
import configparser
from collections import deque
from datetime import datetime, timedelta

import numpy as np

import conf
from db import InfluxDB, datetime_to_nanosec

DB = InfluxDB('swat')
FETCH_SIZE = 1_000


class Smooth:
    def __init__(self, start: datetime, pidx: int, n_aggregate: int, n_cutoff: int):
        self.db_cursor = start
        self.pidx = pidx
        assert n_aggregate > n_cutoff * 2
        self.n_aggregate = n_aggregate
        self.n_cutoff = n_cutoff
        self.bucket: deque = deque(maxlen=n_aggregate)
        self.moving_avg: deque = deque(maxlen=n_aggregate)
        self.buffer: deque = deque(maxlen=FETCH_SIZE)
        while len(self.bucket) < n_aggregate:
            self.push()

    def fetch_to_buffer(self) -> int:
        r = DB.read(conf.EVAL_MEASUREMENT.format(1), self.db_cursor, seconds=FETCH_SIZE).json()
        print(r)
        count = 0
        last_time_str = ''
        for statement in r['results']:
            for s in statement['series']:
                cols = s['columns']
                for v in s['values']:
                    v_dict = dict(zip(cols, v))
                    self.buffer.append(v_dict)
                    last_time_str = v_dict['time']
                    count += 1
        if last_time_str != '':
            self.db_cursor = datetime.strptime(last_time_str,
                                               conf.INFLUX_RETURN_TIME_FORMAT) + timedelta(hours=9
                                                                                           ) + timedelta(seconds=1)
        print(f'\t- fetched {count:,} datapoints')
        return count

    def push(self):
        while True:
            try:
                self.bucket.append(self.buffer.popleft())
                break
            except IndexError:  # when buffer is empty
                self.fetch_to_buffer()

    def check(self, high: int, low: int, ratio: int):
        dist_window = np.array([v['distance'] for v in self.bucket], dtype=np.float32)
        dist_window = np.delete(dist_window, dist_window.argsort()[-self.n_cutoff:])
        self.moving_avg.append(np.sum(dist_window))
        sus = 0
        # write = True
        if len(self.moving_avg) == self.n_aggregate:
            avg_win = np.array(self.moving_avg, dtype=np.float32)
            sus = min(np.percentile(avg_win, high) / np.percentile(avg_win, low) / ratio, 1.0)
            # i_high = abs(avg_win - np.percentile(avg_win, high, interpolation='lower')).argmin()
            # i_low = abs(avg_win - np.percentile(avg_win, low, interpolation='lower')).argmin()
            # write = i_high > i_low
        return datetime.strptime(self.bucket[-1]['time'], '%Y-%m-%dT%H:%M:%SZ') + timedelta(hours=9), self.bucket[-1]['attack'], sus


In [1]:
from swat_dataset import SWaTDataset

In [ ]:
dataset1 = SWaTDataset('dat/normal-P1.dat')

In [ ]:
print(dataset.__getitem__)

In [ ]:
first = dataset1[0]
print(first)

In [ ]:
for x in first.keys():
    print(x)

In [ ]:
firstgiven = first['given']
print(firstgiven)

In [ ]:
firstgiven[0,1:5]

In [ ]:
print(dataset[2])

In [2]:
dataset = SWaTDataset('dat/normal-P5.dat')


In [ ]:
first1 =dataset[0]
for x in first1:
    print(x)

In [ ]:
first1

In [ ]:
import torch 
from torch.utils.data import DataLoader
counter = 0
for i in DataLoader(dataset,batch_size=4096,shuffle=False):
    
    given = i['given']
    predict = i['predict']
    answer = i['answer']
    counter = counter + 1
    print(given.shape)#x
    print(predict.shape)
    print(answer.shape)
    #dxp = torch.zeros(given.shape)
    #print(dxp)
    
    
    print(counter)
    
    #print(predict.shape)#xval
    #print(answer.shape) # y
    



In [ ]:
dxp.shape

In [ ]:
dxp

In [ ]:
batch_size = given.size(0)
batch_size

In [ ]:
given = given.view(batch_size, 90, -1)
given = given.transpose(0,1)
given.shape

In [ ]:
first_data = dataset[0]

In [ ]:
ts, given, predict, answer, attack = first_data

In [ ]:
first_data[:,4:8]

In [ ]:
first_data['given']

In [ ]:
first_data['attack'].shape

In [ ]:
first_data['given'].shape

In [ ]:
first_data['predict'].shape

In [ ]:
first_data['answer'].shape

In [ ]:
first_data['given']

In [ ]:
data_sample = first_data['given']

In [ ]:
data_sample.shape

In [ ]:
data_sample[:,4:8]

In [ ]:
def attack_feature(sensorID,num):
    l=list()
    for i in range(0,10*num,10):
        if sensorID==0:
            for j in range(0,5):
                l.append(i+j)
        if sensorID==1:
            for j in range(5,10):
                l.append(i+j)
        
    return l

In [ ]:
li_attack = attack_feature(int(0),4)
li_attack

In [ ]:
len(li_attack)

In [ ]:
import numpy as np
def MaskForAttackPoints(size):
        a=np.zeros(size[1])
        for i in range(0,13):
            a[i]=1
        return np.tile(a,(size[0],1)).astype(np.float32)

In [ ]:
mask = MaskForAttackPoints(dataset[0]['given'].shape)

In [ ]:
mask

In [ ]:
mask.shape

In [8]:
import copy 
def ObtainListOfParameters(Model):
    l=list()
    for w in Model.parameters():
        l.append(copy.deepcopy(w))
    return l

In [ ]:
def UpdateModel(Model, Alpha,MaxGrad=1,ListOfParam=None):
    if ListOfParam is None:
        for w in Model.parameters():
            w.data=w.data + Alpha* w.grad
    else:
        i=0
        for w in Model.parameters():
            w.data=w.data +Alpha * ListOfParam[i].grad
            i=i+1

In [10]:
def GetLossFunc(batch, enc, dec):
    given = batch['given'].to(torch.device('cuda:0'))
    predict = batch['predict'].to(torch.device('cuda:0'))
    answer = batch['answer'].to(torch.device('cuda:0')) 
    encoder_outs, context = enc(given)
    guess = dec(encoder_outs, context, predict)
    mse_loss = nn.MSELoss()
    loss = mse_loss(guess, answer)

    return loss 

In [29]:
import torch
from torch import nn, optim
from torch.utils.data import DataLoader

import conf
import model
import numpy as np 
from db import InfluxDB, swat_time_to_nanosec

DB = InfluxDB('swat')


class Network():
    def __init__(self, pidx: int, gidx: int, n_features: int, n_hiddens: int):
        self.n_features = n_features
        self.pidx = pidx
        self.gidx = gidx
        self.gpu = torch.device('cuda:{}'.format(gidx - 1))

        self.encoder = model.Encoder(n_inputs=n_features, n_hiddens=n_hiddens).to(self.gpu)
        self.decoder = model.AttentionDecoder(n_hiddens=n_hiddens, n_features=n_features).to(self.gpu)

        self.model_fn = 'checkpoints/SWaT-P{}'.format(pidx)

        self.encoder_optimizer = optim.Adam(self.encoder.parameters(), amsgrad=True)
        self.decoder_optimizer = optim.Adam(self.decoder.parameters(), amsgrad=True)

        self.mse_loss = nn.MSELoss()
    #--------------------------------------------------------------------------------------------------------------
    def get_loss_func(self,x,y):

        loss = self.mse_loss(x, y)

        return loss

    #--------------------------------------------------------------------------------------------------------------
    def GetGradientUsingAutoGrad(enc, dec, TrainingData,batch_size):
        givenbag = []
        predictbag = []
        for batch in DataLoader(TrainingData, batch_size=batch_size, shuffle=True):
            (loss, given, predict) = GetLossFunc(batch, enc, dec)
            given1 = given.clone().detach().requires_grad_(True)
            predict1 = predict.clone().detach().requires_grad_(True)
            grad = torch.autograd.grad(outputs=loss, inputs=(given,predict), retain_graph=True, allow_unused=True)
            loss.backward()
            givenbag.append(given.grad)
            predictbag.append(predict.grad)
        return (grad,enc, dec, givenbag, predictbag)
    
    #--------------------------------------------------------------------------------------------------------------
    def train(self, dataset, batch_size) -> float:
        epoch_loss = 0
        counter = 0
        bag = []
        bag2 = []
        basket = []
        for batch in DataLoader(dataset, batch_size=batch_size, shuffle=True):
            self.encoder_optimizer.zero_grad()
            self.decoder_optimizer.zero_grad()
            given = batch['given'].to(self.gpu)
            predict = batch['predict'].to(self.gpu)
            answer = batch['answer'].to(self.gpu) 
            given = given.clone().detach().requires_grad_(True)
            predict = predict.clone().detach().requires_grad_(True)
            encoder_outs, context = self.encoder(given)
            guess = self.decoder(encoder_outs, context, predict)
            mse_loss = nn.MSELoss()
            loss = mse_loss(guess, answer)
            
            #---------------------------------------------------------
            
          # grad = torch.autograd.grad(outputs=loss, inputs=given,retain_graph=True, allow_unused=True)
          # grad = torch.autograd.grad(outputs=loss, inputs=predict,retain_graph=True, allow_unused=True)      
            grad = torch.autograd.grad(outputs=loss, inputs=(given,predict),retain_graph=True, allow_unused=True)
          # print(grad)
            print('------------------')
            print(given.grad)
          # w = ObtainListOfParameters(self.encoder)
          # print(w)
            
          # print(given)
          # print(predict)
          # print(given.grad)
            counter = counter + 1
            print(counter)
           #loss.backward(inputs= [given,predict])
            loss.backward()
            print('---------------------after backward------------')
            print(given.grad)
           
            #poch_loss += loss.item()
            #epoch_loss += loss.item()
            #answer, guess = self.infer(batch)
            #loss = self.mse_loss(guess, answer)
            #loss = self.get_loss_func(guess, answer)
            #grad = torch.autograd.grad(outputs=loss, inputs=given)
            #loss.backward() # just calculates the gradient 
            #print("loss.data")
            #print(loss.data)
            epoch_loss += loss.item()
            self.encoder_optimizer.step()
            self.decoder_optimizer.step()
          # print(given.grad)
            print('------------------------------------------------------')
        #   a = predict.grad
        #   b = predict.grad
        #   c = a - b
        #   print(predict.grad)
        #   print('---------------------shape-----------------------')
        #   print(given.grad.shape)
        #   print('---------------------subtract---------------')
        #   print(c)
        #   print(c.shape)
        #   dxp = torch.zeros(given.shape)
         #  print(dxp)
         #  print(dxp.shape)
            
         #  bag.append(predict.grad)
            
          # bag = torch.as_tensor(bag)
        
        print('12311111111111111111111111111111111111111111111111111')
       #print(bag)
       #for i in range(len(bag)):
           #basket[i] = bag[i] - bag[i]
           #print(basket[i])
          # print(bag[i]-bag[i])
         #  basket.append(bag[i]-bag[i])
           #print(basket[i])
           #print('---------------------shape-----------------------')
            #rint(basket[i].shape)
            
        #rint(len(basket))
        return epoch_loss

    def eval(self, dataset, batch_size, db_write: bool) -> float:
        epoch_loss = 0
        n_datapoints = 0
        for batch in DataLoader(dataset, batch_size=batch_size, shuffle=False):
            ts = [swat_time_to_nanosec(t) for t in batch['ts']]
            attack = batch['attack']

            answer, guess = self.infer(batch)
            distance = torch.norm(guess - answer, p=conf.EVALUATION_NORM_P, dim=1)
            epoch_loss += torch.sum(distance).item()
            n_datapoints += len(ts)

            if db_write:  # write all distances to influxDB
                col_dist = torch.abs(guess - answer).cpu().numpy()
                fields = {k: col_dist[:, i] for i, k in enumerate(conf.P_SRCS[self.pidx - 1])}
                fields.update({'distance': distance.cpu().tolist()})
                DB.write(conf.EVAL_MEASUREMENT.format(self.pidx), {'attack': attack}, fields, ts)
        return epoch_loss / n_datapoints

    def infer(self, batch):
        given = batch['given'].to(self.gpu)
        predict = batch['predict'].to(self.gpu)
        answer = batch['answer'].to(self.gpu)
        encoder_outs, context = self.encoder(given)
        guess = self.decoder(encoder_outs, context, predict)
        return answer, guess

    def load(self, idx: int) -> float:
        fn = self.model_fn + '-{}.net'.format(idx)
        checkpoint = torch.load(fn)
        self.encoder.load_state_dict(checkpoint['model_encoder'])
        self.decoder.load_state_dict(checkpoint['model_decoder'])
        self.encoder_optimizer.load_state_dict(checkpoint['optimizer_encoder'])
        self.decoder_optimizer.load_state_dict(checkpoint['optimizer_decoder'])
        return checkpoint['min_loss']

    def save(self, idx: int, min_loss: float) -> None:
        fn = self.model_fn + '-{}.net'.format(idx)
        torch.save(
            {
                'min_loss': min_loss,
                'model_encoder': self.encoder.state_dict(),
                'model_decoder': self.decoder.state_dict(),
                'optimizer_encoder': self.encoder_optimizer.state_dict(),
                'optimizer_decoder': self.decoder_optimizer.state_dict(),
            },
            fn
        )

    def train_mode(self) -> None:
        self.encoder.train()
        self.decoder.train()

    def eval_mode(self) -> None:
        self.encoder.eval()
        self.decoder.eval()

In [30]:
pnet = Network(pidx=5, gidx=1, n_features=13, n_hiddens=64)

In [31]:
pnet.train(dataset,batch_size=4096)

------------------
None
1
---------------------after backward------------
tensor([[[ 6.4968e-11, -4.5542e-11, -2.8061e-11,  ...,  2.6130e-11,
           1.6129e-11, -1.1600e-10],
         [ 6.6327e-11, -5.1376e-11, -2.5034e-11,  ...,  3.3448e-11,
           1.6713e-11, -1.2254e-10],
         [ 6.5777e-11, -5.3614e-11, -2.3005e-11,  ...,  3.6406e-11,
           1.6467e-11, -1.2377e-10],
         ...,
         [-3.1613e-13, -5.5044e-11, -4.6572e-11,  ...,  1.5555e-11,
           6.9936e-11, -1.9843e-11],
         [ 3.6658e-13, -3.8295e-11, -3.8390e-11,  ...,  7.3602e-12,
           4.9376e-11, -1.2091e-11],
         [ 1.7694e-12, -1.6958e-11, -2.0280e-11,  ...,  2.4649e-12,
           2.2091e-11, -5.0203e-12]],

        [[ 4.3249e-11, -1.8272e-11, -5.7661e-11,  ..., -1.9255e-11,
           1.1635e-12, -8.2033e-11],
         [ 4.5947e-11, -2.2059e-11, -5.7656e-11,  ..., -1.3936e-11,
           1.3890e-12, -8.6675e-11],
         [ 4.6413e-11, -2.3427e-11, -5.6842e-11,  ..., -1.1275e-11,
  

------------------
None
4
---------------------after backward------------
tensor([[[-1.3098e-11, -7.4146e-11, -1.1966e-10,  ...,  2.3158e-12,
           3.1040e-11, -6.5521e-11],
         [-1.4173e-11, -8.3009e-11, -1.1254e-10,  ...,  1.3343e-11,
           3.7597e-11, -7.1300e-11],
         [-1.4827e-11, -8.6929e-11, -1.0769e-10,  ...,  1.8024e-11,
           4.1553e-11, -7.4137e-11],
         ...,
         [-5.6185e-11, -7.4705e-11, -8.8346e-11,  ...,  9.1814e-12,
           9.0352e-11,  1.3368e-12],
         [-3.8629e-11, -4.9866e-11, -6.6327e-11,  ...,  1.2065e-12,
           6.0786e-11,  1.2828e-12],
         [-1.6349e-11, -2.0883e-11, -3.2469e-11,  ..., -1.5884e-12,
           2.5757e-11,  9.5931e-13]],

        [[-1.0059e-11, -8.2096e-11, -1.3399e-10,  ...,  1.1226e-12,
           2.7141e-11, -7.9412e-11],
         [-1.1117e-11, -9.1399e-11, -1.2597e-10,  ...,  1.3122e-11,
           3.4292e-11, -8.6082e-11],
         [-1.1870e-11, -9.5543e-11, -1.2061e-10,  ...,  1.8155e-11,
  

------------------
None
7
---------------------after backward------------
tensor([[[-1.8585e-10, -2.2245e-10, -4.1041e-10,  ..., -1.1847e-10,
           3.9643e-12, -2.8319e-10],
         [-1.9649e-10, -2.5254e-10, -3.7997e-10,  ..., -8.1548e-11,
           2.8912e-11, -2.9973e-10],
         [-2.0627e-10, -2.6740e-10, -3.6119e-10,  ..., -6.5194e-11,
           4.2360e-11, -3.0896e-10],
         ...,
         [-1.2087e-10, -1.3509e-10, -1.9522e-10,  ...,  3.2146e-12,
           1.3922e-10, -1.1858e-11],
         [-7.4875e-11, -8.2094e-11, -1.3933e-10,  ..., -6.6144e-12,
           9.1715e-11,  1.9991e-12],
         [-3.0060e-11, -3.0841e-11, -6.5595e-11,  ..., -7.6091e-12,
           3.7885e-11,  5.0839e-12]],

        [[-1.8787e-10, -2.2723e-10, -4.1680e-10,  ..., -1.1681e-10,
           3.0611e-12, -2.8898e-10],
         [-1.9899e-10, -2.5699e-10, -3.8681e-10,  ..., -8.0162e-11,
           2.7950e-11, -3.0558e-10],
         [-2.0922e-10, -2.7204e-10, -3.6807e-10,  ..., -6.3580e-11,
  

------------------
None
10
---------------------after backward------------
tensor([[[-1.2420e-09, -9.5178e-10, -1.2859e-09,  ..., -6.3489e-10,
          -3.9415e-10, -1.4110e-09],
         [-1.3464e-09, -1.0765e-09, -1.1852e-09,  ..., -5.1011e-10,
          -3.4016e-10, -1.4630e-09],
         [-1.4358e-09, -1.1442e-09, -1.1199e-09,  ..., -4.5156e-10,
          -3.2143e-10, -1.4959e-09],
         ...,
         [-2.2866e-10, -2.1273e-10, -3.1797e-10,  ..., -1.2851e-11,
           1.6788e-10, -5.7867e-11],
         [-1.0037e-10, -1.0240e-10, -2.2319e-10,  ..., -2.5886e-11,
           1.2202e-10,  3.9886e-12],
         [-2.4146e-11, -2.6501e-11, -1.0481e-10,  ..., -2.2166e-11,
           5.5022e-11,  1.8400e-11]],

        [[-1.3515e-09, -1.0383e-09, -1.2425e-09,  ..., -7.1554e-10,
          -4.2090e-10, -1.6089e-09],
         [-1.4685e-09, -1.1890e-09, -1.1101e-09,  ..., -5.6527e-10,
          -3.5941e-10, -1.6734e-09],
         [-1.5705e-09, -1.2677e-09, -1.0286e-09,  ..., -4.9694e-10,
 

------------------
None
13
---------------------after backward------------
tensor([[[-4.0088e-09, -2.6303e-09, -2.5494e-09,  ..., -2.0738e-09,
          -1.5342e-09, -4.0877e-09],
         [-4.4150e-09, -3.0441e-09, -2.2842e-09,  ..., -1.7561e-09,
          -1.4858e-09, -4.2209e-09],
         [-4.7371e-09, -3.2445e-09, -2.1074e-09,  ..., -1.6010e-09,
          -1.5058e-09, -4.2697e-09],
         ...,
         [ 6.2053e-12, -7.1635e-11, -1.8202e-10,  ...,  3.1171e-11,
           1.9574e-10,  6.5903e-11],
         [ 1.1269e-10,  6.8858e-12, -1.4580e-10,  ...,  5.0423e-12,
           1.7346e-10,  1.0950e-10],
         [ 8.8288e-11,  2.2423e-11, -8.5160e-11,  ..., -8.8513e-12,
           9.4755e-11,  7.1784e-11]],

        [[-4.1015e-09, -2.7110e-09, -2.6651e-09,  ..., -1.9752e-09,
          -1.4423e-09, -3.9764e-09],
         [-4.4942e-09, -3.1015e-09, -2.4030e-09,  ..., -1.6490e-09,
          -1.3458e-09, -4.0933e-09],
         [-4.8008e-09, -3.2903e-09, -2.2313e-09,  ..., -1.4855e-09,
 

------------------
None
16
---------------------after backward------------
tensor([[[-3.6000e-10, -2.3189e-10, -1.9322e-10,  ..., -1.8527e-10,
          -1.6286e-10, -3.2821e-10],
         [-3.7677e-10, -2.5191e-10, -1.6711e-10,  ..., -1.5278e-10,
          -1.5533e-10, -3.1786e-10],
         [-3.7785e-10, -2.4857e-10, -1.4764e-10,  ..., -1.3310e-10,
          -1.5178e-10, -2.9643e-10],
         ...,
         [ 5.4234e-11,  2.0359e-11,  1.8303e-11,  ...,  2.2892e-11,
           2.5517e-11,  2.7635e-11],
         [ 4.2182e-11,  1.4357e-11,  9.9885e-12,  ...,  1.7868e-11,
           2.3422e-11,  2.0871e-11],
         [ 2.2416e-11,  5.9155e-12,  1.4208e-12,  ...,  9.6748e-12,
           1.4137e-11,  9.7576e-12]],

        [[-3.1666e-11, -1.8464e-11, -1.7572e-11,  ..., -2.2186e-11,
          -2.0192e-11, -3.2710e-11],
         [-3.8873e-11, -2.4462e-11, -1.8674e-11,  ..., -2.1449e-11,
          -2.2187e-11, -3.6597e-11],
         [-4.5067e-11, -2.8663e-11, -1.9717e-11,  ..., -2.1067e-11,
 

------------------
None
19
---------------------after backward------------
tensor([[[ 4.2467e-10,  2.8109e-10,  2.2144e-10,  ...,  2.1035e-10,
           1.9972e-10,  3.6597e-10],
         [ 3.9324e-10,  2.6810e-10,  1.7366e-10,  ...,  1.5670e-10,
           1.7179e-10,  3.1191e-10],
         [ 3.4345e-10,  2.2816e-10,  1.3705e-10,  ...,  1.2266e-10,
           1.4914e-10,  2.5030e-10],
         ...,
         [ 5.1185e-12,  5.2374e-12, -3.5124e-13,  ...,  7.5719e-12,
          -5.0932e-13, -1.7458e-11],
         [ 3.9700e-12,  3.0846e-12,  3.2419e-13,  ...,  4.2230e-12,
          -2.3367e-12, -1.5402e-11],
         [ 2.2083e-12, -7.3001e-15,  1.9036e-12,  ...,  4.5467e-13,
          -2.1077e-12, -9.3045e-12]],

        [[ 4.3570e-10,  2.8842e-10,  2.2826e-10,  ...,  2.1878e-10,
           2.0205e-10,  3.7906e-10],
         [ 4.0285e-10,  2.7538e-10,  1.7976e-10,  ...,  1.6357e-10,
           1.7288e-10,  3.2392e-10],
         [ 3.5161e-10,  2.3442e-10,  1.4265e-10,  ...,  1.2841e-10,
 

------------------
None
22
---------------------after backward------------
tensor([[[ 1.2482e-10,  8.3517e-11,  6.6463e-11,  ...,  6.1744e-11,
           6.0444e-11,  1.0376e-10],
         [ 1.0343e-10,  7.0985e-11,  4.7702e-11,  ...,  4.2177e-11,
           4.7055e-11,  7.9220e-11],
         [ 8.0143e-11,  5.3205e-11,  3.4120e-11,  ...,  3.0223e-11,
           3.6650e-11,  5.6127e-11],
         ...,
         [-3.2492e-12, -6.0978e-13, -3.9125e-12,  ..., -2.2209e-13,
          -4.4128e-12, -9.5948e-12],
         [-1.5828e-12, -6.4373e-13, -2.5767e-12,  ..., -6.0765e-13,
          -3.2937e-12, -8.4887e-12],
         [-6.7576e-13, -1.1663e-12, -4.4471e-13,  ..., -1.1277e-12,
          -1.4220e-12, -5.3124e-12]],

        [[ 1.4012e-10,  9.4001e-11,  7.5288e-11,  ...,  6.7233e-11,
           6.8711e-11,  1.1414e-10],
         [ 1.1611e-10,  7.9643e-11,  5.3742e-11,  ...,  4.5504e-11,
           5.3741e-11,  8.6290e-11],
         [ 8.9898e-11,  5.9650e-11,  3.7979e-11,  ...,  3.2262e-11,
 

------------------
None
25
---------------------after backward------------
tensor([[[ 2.9747e-11,  1.9788e-11,  1.6248e-11,  ...,  1.5148e-11,
           1.5370e-11,  2.4398e-11],
         [ 2.3159e-11,  1.5715e-11,  1.1107e-11,  ...,  9.9949e-12,
           1.1424e-11,  1.7411e-11],
         [ 1.6851e-11,  1.0983e-11,  7.5563e-12,  ...,  6.9609e-12,
           8.4625e-12,  1.1494e-11],
         ...,
         [-2.5182e-12, -7.1261e-13, -8.0858e-13,  ..., -7.0598e-13,
          -2.2349e-12, -2.3388e-12],
         [-1.6985e-12, -5.8604e-13, -3.5187e-13,  ..., -6.2800e-13,
          -1.5754e-12, -2.1017e-12],
         [-8.5486e-13, -4.9213e-13,  1.0259e-13,  ..., -4.3420e-13,
          -6.4078e-13, -1.4738e-12]],

        [[ 3.7311e-11,  2.4727e-11,  2.0719e-11,  ...,  1.8537e-11,
           1.8976e-11,  3.0088e-11],
         [ 2.8469e-11,  1.9269e-11,  1.3936e-11,  ...,  1.1909e-11,
           1.3826e-11,  2.0945e-11],
         [ 2.0156e-11,  1.3121e-11,  9.1667e-12,  ...,  7.9783e-12,
 

------------------
None
28
---------------------after backward------------
tensor([[[ 2.8919e-11,  1.9299e-11,  1.5707e-11,  ...,  1.4194e-11,
           1.4469e-11,  2.2317e-11],
         [ 2.1201e-11,  1.4348e-11,  1.0250e-11,  ...,  8.8938e-12,
           9.9971e-12,  1.4827e-11],
         [ 1.4475e-11,  9.3908e-12,  6.6221e-12,  ...,  5.9107e-12,
           6.8824e-12,  8.9559e-12],
         ...,
         [-2.6122e-12, -1.2670e-12, -3.9959e-13,  ..., -9.4002e-13,
          -1.9744e-12,  1.2179e-14],
         [-2.0197e-12, -8.6523e-13, -2.2446e-13,  ..., -8.6101e-13,
          -1.6711e-12,  2.7547e-13],
         [-1.1041e-12, -3.6103e-13, -2.0383e-13,  ..., -6.1464e-13,
          -9.4159e-13,  2.1820e-13]],

        [[ 2.3958e-11,  1.5797e-11,  1.2756e-11,  ...,  1.2526e-11,
           1.2499e-11,  1.9183e-11],
         [ 1.8431e-11,  1.2385e-11,  8.7110e-12,  ...,  8.2858e-12,
           9.1523e-12,  1.3430e-11],
         [ 1.3274e-11,  8.5603e-12,  5.9749e-12,  ...,  5.8279e-12,
 

------------------
None
31
---------------------after backward------------
tensor([[[ 1.0398e-11,  6.8588e-12,  5.7437e-12,  ...,  5.1583e-12,
           5.5389e-12,  7.6966e-12],
         [ 7.5870e-12,  5.0265e-12,  3.7480e-12,  ...,  3.2381e-12,
           3.8736e-12,  4.9485e-12],
         [ 5.0466e-12,  3.1837e-12,  2.3400e-12,  ...,  2.1043e-12,
           2.6048e-12,  2.8174e-12],
         ...,
         [-3.6994e-13, -3.8437e-13, -2.8463e-14,  ..., -7.2204e-14,
          -1.3202e-13,  5.3198e-13],
         [-3.1092e-13, -2.6022e-13, -8.9322e-14,  ..., -8.2726e-14,
          -2.3329e-13,  6.7954e-13],
         [-1.7738e-13, -9.5588e-14, -2.5817e-13,  ..., -7.3213e-14,
          -2.6640e-13,  5.5876e-13]],

        [[ 1.0481e-11,  6.8089e-12,  5.6767e-12,  ...,  5.7638e-12,
           5.6556e-12,  8.3446e-12],
         [ 8.3200e-12,  5.5454e-12,  4.1226e-12,  ...,  4.0117e-12,
           4.3031e-12,  5.9944e-12],
         [ 6.1321e-12,  3.9545e-12,  2.9691e-12,  ...,  2.9475e-12,
 

------------------
None
34
---------------------after backward------------
tensor([[[ 3.5711e-12,  2.2683e-12,  1.9877e-12,  ...,  2.0207e-12,
           1.9619e-12,  2.7266e-12],
         [ 2.8104e-12,  1.8482e-12,  1.4380e-12,  ...,  1.4078e-12,
           1.4946e-12,  1.9229e-12],
         [ 1.9957e-12,  1.2783e-12,  9.9259e-13,  ...,  1.0109e-12,
           1.1052e-12,  1.1893e-12],
         ...,
         [ 2.3356e-12,  6.3356e-13,  9.1179e-13,  ...,  1.1385e-12,
           1.8223e-12,  4.0155e-13],
         [ 1.8513e-12,  4.3120e-13,  6.6066e-13,  ...,  1.0264e-12,
           1.3777e-12,  3.9802e-13],
         [ 1.0051e-12,  2.0846e-13,  2.4497e-13,  ...,  6.7207e-13,
           6.4924e-13,  2.8163e-13]],

        [[ 1.1930e-12,  7.2173e-13,  6.8075e-13,  ...,  8.7263e-13,
           7.4342e-13,  1.0080e-12],
         [ 1.4062e-12,  9.4350e-13,  7.7632e-13,  ...,  8.4742e-13,
           8.0084e-13,  1.0391e-12],
         [ 1.3065e-12,  8.8056e-13,  7.2178e-13,  ...,  7.6136e-13,
 

------------------
None
37
---------------------after backward------------
tensor([[[ 5.8509e-12,  3.8586e-12,  3.3397e-12,  ...,  2.9755e-12,
           3.0999e-12,  4.3684e-12],
         [ 3.4678e-12,  2.3087e-12,  1.7292e-12,  ...,  1.5296e-12,
           1.7809e-12,  2.3083e-12],
         [ 1.7962e-12,  1.1228e-12,  7.9202e-13,  ...,  7.8849e-13,
           9.5460e-13,  1.0191e-12],
         ...,
         [ 4.3161e-13,  7.7468e-14,  1.6892e-13,  ...,  2.6419e-13,
           3.7465e-13, -1.0156e-13],
         [ 3.3465e-13,  3.7077e-14,  1.4413e-13,  ...,  2.3382e-13,
           2.5915e-13, -1.0168e-13],
         [ 1.5297e-13, -1.2964e-14,  1.1512e-13,  ...,  1.1254e-13,
           1.1493e-13, -7.8839e-14]],

        [[ 1.0954e-12,  7.3379e-13,  5.7785e-13,  ...,  5.5177e-13,
           5.4906e-13,  7.4608e-13],
         [ 6.9529e-13,  4.5829e-13,  3.0356e-13,  ...,  3.0159e-13,
           3.2641e-13,  4.0034e-13],
         [ 3.9326e-13,  2.3808e-13,  1.3929e-13,  ...,  1.6355e-13,
 

------------------
None
40
---------------------after backward------------
tensor([[[ 8.8397e-12,  5.9053e-12,  5.0346e-12,  ...,  4.3927e-12,
           4.6584e-12,  6.6222e-12],
         [ 4.8072e-12,  3.2266e-12,  2.3724e-12,  ...,  2.0413e-12,
           2.4490e-12,  3.2247e-12],
         [ 2.2246e-12,  1.3830e-12,  9.4465e-13,  ...,  9.1606e-13,
           1.1624e-12,  1.2759e-12],
         ...,
         [-7.7296e-13, -2.8388e-13, -2.1429e-13,  ..., -3.3408e-13,
          -5.7141e-13, -3.2583e-13],
         [-6.4004e-13, -2.2486e-13, -1.0421e-13,  ..., -3.2044e-13,
          -4.7664e-13, -3.3906e-13],
         [-4.0232e-13, -1.6567e-13,  7.2877e-14,  ..., -2.8102e-13,
          -2.3094e-13, -2.7286e-13]],

        [[ 2.1960e-12,  1.5137e-12,  1.2522e-12,  ...,  1.0522e-12,
           1.1019e-12,  1.6279e-12],
         [ 1.1495e-12,  7.8849e-13,  5.5202e-13,  ...,  4.6183e-13,
           5.4815e-13,  7.6805e-13],
         [ 5.2625e-13,  3.3119e-13,  2.0182e-13,  ...,  1.8920e-13,
 

------------------
None
43
---------------------after backward------------
tensor([[[ 6.2348e-12,  4.1819e-12,  3.6399e-12,  ...,  2.9225e-12,
           3.2498e-12,  4.4204e-12],
         [ 3.0083e-12,  1.9458e-12,  1.4906e-12,  ...,  1.1683e-12,
           1.5151e-12,  1.8798e-12],
         [ 1.1246e-12,  6.0339e-13,  4.3268e-13,  ...,  3.6763e-13,
           5.5093e-13,  6.0136e-13],
         ...,
         [-2.9778e-12, -1.0201e-12, -1.0089e-12,  ..., -1.2974e-12,
          -2.2454e-12, -3.8746e-13],
         [-2.4871e-12, -7.5865e-13, -7.4491e-13,  ..., -1.2192e-12,
          -1.8752e-12, -3.7784e-13],
         [-1.4740e-12, -4.4837e-13, -2.8109e-13,  ..., -8.9169e-13,
          -1.0220e-12, -2.7503e-13]],

        [[ 7.0743e-12,  4.7203e-12,  4.0652e-12,  ...,  3.5040e-12,
           3.7591e-12,  5.2703e-12],
         [ 3.6054e-12,  2.4058e-12,  1.7966e-12,  ...,  1.5241e-12,
           1.8593e-12,  2.4083e-12],
         [ 1.5048e-12,  9.1547e-13,  6.3739e-13,  ...,  6.1272e-13,
 

------------------
None
46
---------------------after backward------------
tensor([[[ 3.4745e-12,  2.3268e-12,  2.0247e-12,  ...,  1.7146e-12,
           1.8296e-12,  2.6041e-12],
         [ 1.6681e-12,  1.1251e-12,  8.5528e-13,  ...,  7.0055e-13,
           8.4941e-13,  1.1276e-12],
         [ 6.1648e-13,  3.8209e-13,  2.6619e-13,  ...,  2.4900e-13,
           3.2177e-13,  3.4992e-13],
         ...,
         [-5.6170e-14, -4.5375e-14,  2.7650e-14,  ..., -7.3409e-14,
          -3.8702e-14, -1.1683e-13],
         [-4.8982e-14, -2.8975e-14,  6.5182e-14,  ..., -8.0950e-14,
          -2.4661e-14, -1.2965e-13],
         [-3.6692e-14, -1.3123e-14,  9.9922e-14,  ..., -8.9877e-14,
           1.3660e-14, -1.1174e-13]],

        [[ 6.1747e-12,  4.0897e-12,  3.5546e-12,  ...,  3.0250e-12,
           3.2680e-12,  4.5325e-12],
         [ 3.0140e-12,  1.9867e-12,  1.5086e-12,  ...,  1.2523e-12,
           1.5481e-12,  1.9615e-12],
         [ 1.1341e-12,  6.6591e-13,  4.6989e-13,  ...,  4.4688e-13,
 

------------------------------------------------------
------------------
None
49
---------------------after backward------------
tensor([[[-7.3258e-13, -4.7990e-13, -4.1760e-13,  ..., -3.7261e-13,
          -3.9812e-13, -5.0279e-13],
         [-2.7088e-13, -1.6697e-13, -1.2238e-13,  ..., -1.2982e-13,
          -1.5036e-13, -1.6840e-13],
         [-6.7282e-14, -2.8863e-14, -2.1555e-14,  ..., -3.9712e-14,
          -4.8070e-14, -4.5548e-14],
         ...,
         [ 5.8531e-13,  1.4421e-13,  1.7104e-13,  ...,  1.8499e-13,
           4.1269e-13,  7.7700e-14],
         [ 4.9187e-13,  1.0811e-13,  1.3515e-13,  ...,  1.7553e-13,
           3.4706e-13,  7.6188e-14],
         [ 2.9417e-13,  7.4101e-14,  5.8769e-14,  ...,  1.4668e-13,
           1.7757e-13,  5.0771e-14]],

        [[ 2.9719e-12,  1.9556e-12,  1.6736e-12,  ...,  1.4501e-12,
           1.5761e-12,  2.1633e-12],
         [ 1.4789e-12,  9.6746e-13,  7.2891e-13,  ...,  6.0643e-13,
           7.5671e-13,  9.4153e-13],
         [ 5.5

------------------
None
52
---------------------after backward------------
tensor([[[ 4.9974e-13,  3.4507e-13,  2.6127e-13,  ...,  2.7841e-13,
           3.2921e-13,  4.6949e-13],
         [ 4.8513e-13,  3.5679e-13,  2.5928e-13,  ...,  2.2707e-13,
           2.7758e-13,  3.6265e-13],
         [ 3.3868e-13,  2.4696e-13,  1.7486e-13,  ...,  1.6425e-13,
           1.9291e-13,  1.9025e-13],
         ...,
         [ 1.8876e-12,  5.3749e-13,  5.8234e-13,  ...,  7.5989e-13,
           1.3986e-12,  1.8984e-13],
         [ 1.5822e-12,  3.9484e-13,  4.2911e-13,  ...,  7.0936e-13,
           1.1629e-12,  1.8947e-13],
         [ 9.3265e-13,  2.3503e-13,  1.7172e-13,  ...,  5.2635e-13,
           6.1049e-13,  1.3965e-13]],

        [[ 3.0389e-13,  2.1500e-13,  1.4650e-13,  ...,  1.7426e-13,
           2.1984e-13,  3.0784e-13],
         [ 3.7818e-13,  2.8076e-13,  2.0091e-13,  ...,  1.7625e-13,
           2.1928e-13,  2.8180e-13],
         [ 2.8776e-13,  2.0986e-13,  1.4952e-13,  ...,  1.3849e-13,
 

------------------
None
55
---------------------after backward------------
tensor([[[-1.0048e-11, -6.7462e-12, -5.6791e-12,  ..., -4.9019e-12,
          -5.1557e-12, -7.1075e-12],
         [-4.6260e-12, -3.0574e-12, -2.2854e-12,  ..., -1.9734e-12,
          -2.2941e-12, -2.9407e-12],
         [-1.6166e-12, -9.4849e-13, -6.6015e-13,  ..., -6.9594e-13,
          -8.5242e-13, -8.3789e-13],
         ...,
         [-5.4833e-13, -6.9046e-14, -4.4141e-13,  ..., -1.8811e-13,
          -5.1561e-13,  2.7622e-13],
         [-4.9230e-13, -9.3484e-14, -4.7306e-13,  ..., -1.3248e-13,
          -4.3557e-13,  2.5455e-13],
         [-3.0844e-13, -3.8246e-14, -4.1301e-13,  ..., -7.2090e-15,
          -2.9450e-13,  1.8650e-13]],

        [[-3.4283e-13, -2.0639e-13, -1.6080e-13,  ..., -1.1472e-13,
          -7.1758e-14, -8.2113e-14],
         [ 6.3417e-14,  9.4518e-14,  8.6878e-14,  ...,  7.3252e-14,
           8.5525e-14,  1.3716e-13],
         [ 1.9362e-13,  1.7908e-13,  1.3906e-13,  ...,  1.2709e-13,
 

------------------
None
58
---------------------after backward------------
tensor([[[-1.8077e-12, -1.2170e-12, -1.0831e-12,  ..., -8.9129e-13,
          -9.2425e-13, -1.3396e-12],
         [-8.0376e-13, -5.5407e-13, -4.2693e-13,  ..., -3.4307e-13,
          -3.9740e-13, -5.3997e-13],
         [-2.6336e-13, -1.7328e-13, -1.1305e-13,  ..., -1.1477e-13,
          -1.3858e-13, -1.4245e-13],
         ...,
         [-5.1332e-14,  3.8928e-14, -1.6365e-13,  ...,  3.1406e-14,
          -2.9269e-14,  1.5366e-13],
         [-5.7830e-14,  3.3094e-14, -1.9146e-13,  ...,  3.2525e-14,
          -4.3757e-14,  1.5938e-13],
         [-3.6581e-14,  3.8893e-14, -1.7188e-13,  ...,  3.1601e-14,
          -4.7289e-14,  1.3656e-13]],

        [[-8.8182e-13, -6.1528e-13, -5.9258e-13,  ..., -4.9076e-13,
          -5.8669e-13, -8.0938e-13],
         [-5.0758e-13, -3.9714e-13, -3.2811e-13,  ..., -2.6410e-13,
          -3.2479e-13, -4.3170e-13],
         [-2.8224e-13, -2.3688e-13, -1.7476e-13,  ..., -1.6371e-13,
 

------------------
None
61
---------------------after backward------------
tensor([[[-1.1092e-12, -7.5805e-13, -7.1856e-13,  ..., -5.7790e-13,
          -6.6112e-13, -9.3591e-13],
         [-6.7400e-13, -4.9771e-13, -4.1495e-13,  ..., -3.1095e-13,
          -3.8317e-13, -5.0549e-13],
         [-3.5235e-13, -2.6808e-13, -2.0355e-13,  ..., -1.7460e-13,
          -2.1079e-13, -2.0809e-13],
         ...,
         [-1.5497e-12, -4.3977e-13, -6.6696e-13,  ..., -6.1716e-13,
          -1.1476e-12, -2.0611e-14],
         [-1.3260e-12, -3.1959e-13, -5.4750e-13,  ..., -5.7915e-13,
          -9.8658e-13, -1.0268e-14],
         [-7.9279e-13, -1.7101e-13, -3.0019e-13,  ..., -4.2851e-13,
          -5.5222e-13,  8.5094e-15]],

        [[-6.3148e-13, -4.2906e-13, -4.1971e-13,  ..., -3.2802e-13,
          -3.4213e-13, -5.3440e-13],
         [-3.2792e-13, -2.4689e-13, -2.1005e-13,  ..., -1.5055e-13,
          -1.7183e-13, -2.5688e-13],
         [-1.3919e-13, -1.1233e-13, -8.2976e-14,  ..., -7.1720e-14,
 

------------------
None
64
---------------------after backward------------
tensor([[[-4.1111e-12, -2.7526e-12, -2.3082e-12,  ..., -2.0222e-12,
          -2.2591e-12, -2.9866e-12],
         [-1.9023e-12, -1.2675e-12, -9.3184e-13,  ..., -8.1157e-13,
          -1.0174e-12, -1.2273e-12],
         [-6.6074e-13, -3.9952e-13, -2.6610e-13,  ..., -2.8392e-13,
          -3.7342e-13, -3.4280e-13],
         ...,
         [-1.2400e-12, -3.6222e-13, -4.4562e-13,  ..., -5.1047e-13,
          -9.8149e-13, -7.5744e-14],
         [-1.0600e-12, -2.9073e-13, -3.5760e-13,  ..., -4.5475e-13,
          -8.2377e-13, -7.8444e-14],
         [-6.4576e-13, -1.7757e-13, -1.9971e-13,  ..., -3.0255e-13,
          -4.6404e-13, -6.0299e-14]],

        [[-7.7319e-13, -5.0238e-13, -4.3969e-13,  ..., -3.6254e-13,
          -3.6513e-13, -5.2773e-13],
         [-2.8412e-13, -1.7731e-13, -1.3786e-13,  ..., -1.0498e-13,
          -1.2467e-13, -1.6454e-13],
         [-3.3336e-14, -5.1850e-15, -1.6286e-15,  ..., -3.3016e-15,
 

------------------
None
67
---------------------after backward------------
tensor([[[ 5.1665e-12,  3.4435e-12,  2.9131e-12,  ...,  2.5661e-12,
           2.7817e-12,  3.7598e-12],
         [ 2.3262e-12,  1.5515e-12,  1.1113e-12,  ...,  9.8548e-13,
           1.2119e-12,  1.4842e-12],
         [ 7.5680e-13,  4.5381e-13,  2.6460e-13,  ...,  3.0819e-13,
           4.1253e-13,  3.7976e-13],
         ...,
         [ 7.4062e-13,  1.8989e-13,  2.8092e-13,  ...,  2.5499e-13,
           5.9222e-13,  3.7028e-14],
         [ 6.3946e-13,  1.5283e-13,  2.4024e-13,  ...,  2.2083e-13,
           4.9722e-13,  3.4818e-14],
         [ 3.9283e-13,  8.0289e-14,  1.5759e-13,  ...,  1.4012e-13,
           2.8916e-13,  1.8294e-14]],

        [[-5.1146e-12, -3.4098e-12, -2.7976e-12,  ..., -2.4832e-12,
          -2.7055e-12, -3.5651e-12],
         [-2.0853e-12, -1.3487e-12, -9.3956e-13,  ..., -8.5933e-13,
          -1.0648e-12, -1.2629e-12],
         [-5.2371e-13, -2.6707e-13, -1.3296e-13,  ..., -1.9707e-13,
 

------------------
None
70
---------------------after backward------------
tensor([[[-6.1677e-12, -4.1330e-12, -3.3564e-12,  ..., -2.9720e-12,
          -3.1882e-12, -4.2541e-12],
         [-2.2662e-12, -1.4668e-12, -9.8293e-13,  ..., -9.2624e-13,
          -1.1208e-12, -1.3533e-12],
         [-3.9794e-13, -1.7372e-13, -3.0196e-14,  ..., -1.4114e-13,
          -2.0108e-13, -1.4439e-13],
         ...,
         [ 5.2972e-13,  1.3149e-13,  7.4127e-14,  ...,  3.2787e-13,
           3.2807e-13,  1.6159e-13],
         [ 4.2134e-13,  3.5521e-14, -4.2491e-14,  ...,  3.5952e-13,
           2.5466e-13,  1.4829e-13],
         [ 2.1124e-13,  3.2533e-15, -1.6367e-13,  ...,  3.5092e-13,
           6.6129e-14,  1.0561e-13]],

        [[-2.9454e-12, -2.0183e-12, -1.8521e-12,  ..., -1.4865e-12,
          -1.7445e-12, -2.3398e-12],
         [-1.4049e-12, -1.0128e-12, -8.2183e-13,  ..., -6.3677e-13,
          -8.1574e-13, -1.0334e-12],
         [-5.6470e-13, -4.1624e-13, -3.1394e-13,  ..., -2.7858e-13,
 

------------------
None
73
---------------------after backward------------
tensor([[[ 5.8516e-12,  3.9257e-12,  3.3224e-12,  ...,  2.9478e-12,
           3.1755e-12,  4.3716e-12],
         [ 2.6348e-12,  1.7914e-12,  1.2905e-12,  ...,  1.1424e-12,
           1.3790e-12,  1.7525e-12],
         [ 8.7750e-13,  5.5384e-13,  3.3639e-13,  ...,  3.7824e-13,
           4.8175e-13,  4.7044e-13],
         ...,
         [ 1.6857e-12,  4.7575e-13,  6.0682e-13,  ...,  6.6117e-13,
           1.2561e-12,  1.4530e-13],
         [ 1.4383e-12,  3.4636e-13,  4.6831e-13,  ...,  6.0684e-13,
           1.0610e-12,  1.2274e-13],
         [ 8.6933e-13,  1.8159e-13,  2.4535e-13,  ...,  4.2965e-13,
           5.9051e-13,  6.9330e-14]],

        [[ 3.4996e-12,  2.3852e-12,  1.9802e-12,  ...,  1.7410e-12,
           1.8928e-12,  2.6093e-12],
         [ 1.7220e-12,  1.1859e-12,  8.3966e-13,  ...,  7.2970e-13,
           9.0136e-13,  1.1335e-12],
         [ 6.6289e-13,  4.2481e-13,  2.5968e-13,  ...,  2.7233e-13,
 

------------------
None
76
---------------------after backward------------
tensor([[[ 5.8702e-12,  3.9413e-12,  3.3383e-12,  ...,  2.9248e-12,
           3.1158e-12,  4.3249e-12],
         [ 2.5241e-12,  1.7164e-12,  1.2204e-12,  ...,  1.0749e-12,
           1.2871e-12,  1.6457e-12],
         [ 7.5771e-13,  4.7140e-13,  2.6144e-13,  ...,  3.1582e-13,
           4.0299e-13,  3.8560e-13],
         ...,
         [ 1.0463e-12,  2.7161e-13,  4.2548e-13,  ...,  3.6314e-13,
           7.7380e-13,  3.5394e-14],
         [ 8.9771e-13,  1.9947e-13,  3.5745e-13,  ...,  3.1924e-13,
           6.5989e-13,  2.3706e-14],
         [ 5.5016e-13,  9.6728e-14,  2.2534e-13,  ...,  2.0678e-13,
           3.8282e-13, -6.0543e-16]],

        [[ 5.2579e-12,  3.4903e-12,  2.9443e-12,  ...,  2.5731e-12,
           2.7446e-12,  3.7460e-12],
         [ 2.0752e-12,  1.3744e-12,  9.4962e-13,  ...,  8.5739e-13,
           1.0325e-12,  1.2782e-12],
         [ 4.7504e-13,  2.6305e-13,  9.6401e-14,  ...,  1.7911e-13,
 

------------------
None
79
---------------------after backward------------
tensor([[[-2.2683e-10, -1.5828e-10, -2.2184e-10,  ..., -2.5231e-10,
          -1.9110e-10, -2.8617e-10],
         [-3.8992e-10, -2.7869e-10, -3.4319e-10,  ..., -3.4818e-10,
          -2.8109e-10, -4.1885e-10],
         [-4.4799e-10, -3.1613e-10, -3.7974e-10,  ..., -3.7273e-10,
          -3.0717e-10, -4.5587e-10],
         ...,
         [-5.8301e-11, -2.2923e-11, -5.1309e-11,  ..., -4.0862e-11,
          -5.1043e-11, -3.7044e-11],
         [-4.7457e-11, -1.4408e-11, -3.9446e-11,  ..., -3.4352e-11,
          -4.1191e-11, -2.8339e-11],
         [-2.7494e-11, -5.8571e-12, -2.0387e-11,  ..., -2.4147e-11,
          -2.1235e-11, -1.5243e-11]],

        [[-5.9033e-12, -4.0190e-12, -3.4555e-12,  ..., -2.9156e-12,
          -3.3199e-12, -4.4221e-12],
         [-2.6456e-12, -1.8354e-12, -1.3638e-12,  ..., -1.1471e-12,
          -1.4437e-12, -1.7900e-12],
         [-9.1818e-13, -6.1224e-13, -4.0250e-13,  ..., -4.1369e-13,
 

------------------
None
82
---------------------after backward------------
tensor([[[ 5.9604e-12,  3.9647e-12,  3.3640e-12,  ...,  2.9352e-12,
           3.0885e-12,  4.1914e-12],
         [ 2.1774e-12,  1.4398e-12,  9.7449e-13,  ...,  9.0676e-13,
           1.0684e-12,  1.3027e-12],
         [ 3.8582e-13,  1.9692e-13,  1.9964e-14,  ...,  1.4226e-13,
           1.8410e-13,  1.2738e-13],
         ...,
         [-2.8860e-13, -9.6776e-14, -1.4586e-15,  ..., -2.5009e-13,
          -2.2384e-13, -1.5301e-13],
         [-2.3124e-13, -3.7699e-14,  8.4829e-14,  ..., -2.8555e-13,
          -1.7431e-13, -1.3939e-13],
         [-1.1044e-13, -2.5141e-14,  1.6202e-13,  ..., -2.7659e-13,
          -4.2685e-14, -1.0573e-13]],

        [[ 4.9850e-12,  3.3726e-12,  2.8292e-12,  ...,  2.5156e-12,
           2.7192e-12,  3.7576e-12],
         [ 2.3028e-12,  1.5788e-12,  1.1359e-12,  ...,  1.0024e-12,
           1.2143e-12,  1.5540e-12],
         [ 8.2873e-13,  5.2906e-13,  3.4311e-13,  ...,  3.6128e-13,
 

------------------
None
85
---------------------after backward------------
tensor([[[ 5.9333e-12,  4.0465e-12,  3.4620e-12,  ...,  3.0536e-12,
           3.3001e-12,  4.6609e-12],
         [ 2.8898e-12,  2.0204e-12,  1.5150e-12,  ...,  1.2943e-12,
           1.5528e-12,  2.0718e-12],
         [ 1.1579e-12,  7.7660e-13,  5.5217e-13,  ...,  5.2628e-13,
           6.4917e-13,  7.0466e-13],
         ...,
         [ 2.5572e-12,  6.7285e-13,  9.0450e-13,  ...,  1.0888e-12,
           1.8435e-12,  2.2448e-13],
         [ 2.1534e-12,  4.3014e-13,  6.4494e-13,  ...,  1.0340e-12,
           1.5578e-12,  1.6644e-13],
         [ 1.2690e-12,  1.9529e-13,  2.7585e-13,  ...,  7.6971e-13,
           8.2291e-13,  8.1040e-14]],

        [[ 4.9522e-12,  3.3386e-12,  2.8519e-12,  ...,  2.5098e-12,
           2.6981e-12,  3.7256e-12],
         [ 2.2150e-12,  1.5141e-12,  1.1153e-12,  ...,  9.7466e-13,
           1.1689e-12,  1.4988e-12],
         [ 7.5658e-13,  4.8253e-13,  3.1947e-13,  ...,  3.3501e-13,
 

------------------
None
88
---------------------after backward------------
tensor([[[ 7.5528e-12,  5.1423e-12,  4.3830e-12,  ...,  3.8758e-12,
           4.1557e-12,  5.8866e-12],
         [ 3.6516e-12,  2.5401e-12,  1.8997e-12,  ...,  1.6295e-12,
           1.9415e-12,  2.5947e-12],
         [ 1.4469e-12,  9.5814e-13,  6.8389e-13,  ...,  6.5309e-13,
           8.0436e-13,  8.7410e-13],
         ...,
         [ 2.7846e-12,  7.0200e-13,  9.9975e-13,  ...,  1.1842e-12,
           2.0121e-12,  2.3121e-13],
         [ 2.3458e-12,  4.3817e-13,  7.1961e-13,  ...,  1.1236e-12,
           1.6973e-12,  1.6768e-13],
         [ 1.3820e-12,  1.8766e-13,  3.1881e-13,  ...,  8.3146e-13,
           8.9113e-13,  7.8119e-14]],

        [[-2.3491e-12, -1.5674e-12, -1.3140e-12,  ..., -1.1540e-12,
          -1.1393e-12, -1.5854e-12],
         [-7.0111e-13, -4.5805e-13, -2.9342e-13,  ..., -3.0151e-13,
          -3.1188e-13, -3.9264e-13],
         [-2.8288e-14,  6.7859e-15,  5.2268e-14,  ..., -1.8438e-14,
 

------------------
None
91
---------------------after backward------------
tensor([[[ 5.5425e-12,  3.7291e-12,  3.1226e-12,  ...,  2.7906e-12,
           3.0054e-12,  4.1086e-12],
         [ 2.5014e-12,  1.6888e-12,  1.2110e-12,  ...,  1.0856e-12,
           1.3140e-12,  1.6490e-12],
         [ 8.7042e-13,  5.3432e-13,  3.4884e-13,  ...,  3.7550e-13,
           4.8910e-13,  4.7269e-13],
         ...,
         [ 8.3335e-13,  2.2139e-13,  3.1579e-13,  ...,  3.2194e-13,
           6.2875e-13,  4.6797e-14],
         [ 7.1800e-13,  1.6065e-13,  2.5779e-13,  ...,  2.8362e-13,
           5.3501e-13,  3.9178e-14],
         [ 4.5269e-13,  7.1634e-14,  1.5638e-13,  ...,  1.8200e-13,
           3.0795e-13,  2.0097e-14]],

        [[ 5.5220e-12,  3.7224e-12,  3.2092e-12,  ...,  2.8098e-12,
           3.0074e-12,  4.1971e-12],
         [ 2.5007e-12,  1.7175e-12,  1.2892e-12,  ...,  1.1094e-12,
           1.3199e-12,  1.7245e-12],
         [ 8.9051e-13,  5.7647e-13,  4.0487e-13,  ...,  4.0202e-13,
 

------------------
None
94
---------------------after backward------------
tensor([[[ 6.6131e-12,  4.4523e-12,  3.8371e-12,  ...,  3.3950e-12,
           3.6305e-12,  5.0240e-12],
         [ 2.8697e-12,  1.9662e-12,  1.4637e-12,  ...,  1.2919e-12,
           1.5291e-12,  1.9784e-12],
         [ 9.5068e-13,  6.1191e-13,  4.1717e-13,  ...,  4.4119e-13,
           5.3843e-13,  5.5341e-13],
         ...,
         [ 1.3557e-12,  3.6375e-13,  5.9772e-13,  ...,  5.2964e-13,
           9.7387e-13,  1.6151e-14],
         [ 1.1523e-12,  2.3978e-13,  4.8645e-13,  ...,  4.7424e-13,
           8.3708e-13, -1.2019e-14],
         [ 6.9863e-13,  8.8794e-14,  2.9715e-13,  ...,  3.0126e-13,
           4.6937e-13, -2.7609e-14]],

        [[ 5.5852e-12,  3.7773e-12,  3.2751e-12,  ...,  2.8678e-12,
           3.0801e-12,  4.2987e-12],
         [ 2.5203e-12,  1.7420e-12,  1.3197e-12,  ...,  1.1357e-12,
           1.3494e-12,  1.7723e-12],
         [ 9.0045e-13,  5.9287e-13,  4.2231e-13,  ...,  4.1728e-13,
 

------------------
None
97
---------------------after backward------------
tensor([[[ 5.6873e-12,  3.7999e-12,  3.1646e-12,  ...,  2.8226e-12,
           2.9988e-12,  4.0666e-12],
         [ 2.2411e-12,  1.4907e-12,  1.0174e-12,  ...,  9.5622e-13,
           1.1322e-12,  1.3934e-12],
         [ 5.7725e-13,  3.2837e-13,  1.5331e-13,  ...,  2.4059e-13,
           3.0780e-13,  2.6861e-13],
         ...,
         [ 3.6890e-13,  1.2984e-13,  1.5089e-13,  ...,  7.1770e-14,
           2.8971e-13,  1.1445e-15],
         [ 3.2075e-13,  1.2096e-13,  1.5427e-13,  ...,  2.7546e-14,
           2.5219e-13,  4.2853e-15],
         [ 2.2266e-13,  6.4021e-14,  1.4196e-13,  ..., -2.9326e-14,
           1.8035e-13, -7.7011e-16]],

        [[ 7.6064e-12,  5.1193e-12,  4.3424e-12,  ...,  3.8304e-12,
           4.0897e-12,  5.6241e-12],
         [ 3.2906e-12,  2.2314e-12,  1.6110e-12,  ...,  1.4310e-12,
           1.7142e-12,  2.1690e-12],
         [ 1.0612e-12,  6.5692e-13,  4.1422e-13,  ...,  4.5728e-13,
 

------------------
None
100
---------------------after backward------------
tensor([[[ 5.5532e-12,  3.7107e-12,  3.1168e-12,  ...,  2.7668e-12,
           2.9355e-12,  3.9792e-12],
         [ 2.2200e-12,  1.4771e-12,  1.0296e-12,  ...,  9.5492e-13,
           1.1289e-12,  1.3880e-12],
         [ 5.9364e-13,  3.4002e-13,  1.7586e-13,  ...,  2.5104e-13,
           3.1885e-13,  2.8167e-13],
         ...,
         [ 1.5309e-13,  4.4664e-14,  1.1478e-13,  ..., -1.0227e-14,
           1.0894e-13, -6.2338e-14],
         [ 1.3907e-13,  5.4120e-14,  1.4143e-13,  ..., -5.1375e-14,
           9.6103e-14, -5.0705e-14],
         [ 1.1128e-13,  2.0415e-14,  1.4912e-13,  ..., -8.9437e-14,
           8.6562e-14, -3.7108e-14]],

        [[-2.0214e-11, -1.3743e-11, -1.2332e-11,  ..., -9.9203e-12,
          -1.1389e-11, -1.5187e-11],
         [-9.7000e-12, -6.6819e-12, -5.3371e-12,  ..., -4.1518e-12,
          -5.3570e-12, -6.5678e-12],
         [-3.7398e-12, -2.4519e-12, -1.8595e-12,  ..., -1.5923e-12,


------------------
None
103
---------------------after backward------------
tensor([[[ 1.1302e-11,  7.6751e-12,  6.4710e-12,  ...,  5.7432e-12,
           6.1889e-12,  8.6325e-12],
         [ 5.3425e-12,  3.6715e-12,  2.7009e-12,  ...,  2.3463e-12,
           2.8402e-12,  3.6911e-12],
         [ 2.0318e-12,  1.3030e-12,  9.1279e-13,  ...,  8.8805e-13,
           1.1335e-12,  1.1875e-12],
         ...,
         [ 2.8026e-12,  6.1260e-13,  9.9286e-13,  ...,  1.1554e-12,
           2.0484e-12,  2.2725e-13],
         [ 2.3791e-12,  3.6424e-13,  7.2274e-13,  ...,  1.0922e-12,
           1.7387e-12,  1.7334e-13],
         [ 1.4211e-12,  1.3286e-13,  3.3953e-13,  ...,  7.9713e-13,
           9.2444e-13,  8.7341e-14]],

        [[-1.7168e-11, -1.1655e-11, -1.0360e-11,  ..., -8.3694e-12,
          -9.1489e-12, -1.2765e-11],
         [-7.9688e-12, -5.4937e-12, -4.3182e-12,  ..., -3.3728e-12,
          -4.1149e-12, -5.3514e-12],
         [-2.9278e-12, -1.9085e-12, -1.4082e-12,  ..., -1.2320e-12,


------------------
None
106
---------------------after backward------------
tensor([[[ 5.5728e-12,  3.7477e-12,  3.1954e-12,  ...,  2.8089e-12,
           2.9919e-12,  4.1139e-12],
         [ 2.2723e-12,  1.5410e-12,  1.1132e-12,  ...,  9.9762e-13,
           1.1790e-12,  1.4988e-12],
         [ 6.5307e-13,  4.0272e-13,  2.4335e-13,  ...,  2.9152e-13,
           3.5973e-13,  3.4887e-13],
         ...,
         [ 4.5354e-13,  1.0412e-13,  2.7175e-13,  ...,  1.3091e-13,
           3.2175e-13, -7.0347e-14],
         [ 3.9304e-13,  7.0984e-14,  2.5455e-13,  ...,  9.3071e-14,
           2.8929e-13, -7.1292e-14],
         [ 2.5172e-13,  9.8367e-15,  1.9782e-13,  ...,  1.6963e-14,
           1.8151e-13, -5.3662e-14]],

        [[-1.2244e-11, -8.3064e-12, -7.0546e-12,  ..., -5.9801e-12,
          -6.4139e-12, -8.9230e-12],
         [-5.3153e-12, -3.6242e-12, -2.6675e-12,  ..., -2.2531e-12,
          -2.6896e-12, -3.4776e-12],
         [-1.7510e-12, -1.0941e-12, -7.2862e-13,  ..., -7.4115e-13,


------------------
None
109
---------------------after backward------------
tensor([[[ 9.0315e-12,  6.1073e-12,  5.1168e-12,  ...,  4.5130e-12,
           4.8459e-12,  6.6839e-12],
         [ 3.9939e-12,  2.7141e-12,  1.9417e-12,  ...,  1.7155e-12,
           2.0772e-12,  2.6316e-12],
         [ 1.3448e-12,  8.3123e-13,  5.3176e-13,  ...,  5.6664e-13,
           7.3725e-13,  7.2700e-13],
         ...,
         [ 8.6343e-13,  1.4328e-13,  3.7449e-13,  ...,  2.8254e-13,
           6.3168e-13, -1.0076e-14],
         [ 7.5164e-13,  8.3401e-14,  3.2386e-13,  ...,  2.4067e-13,
           5.5336e-13, -1.4853e-14],
         [ 4.7575e-13,  3.2115e-15,  2.1829e-13,  ...,  1.3998e-13,
           3.2677e-13, -2.3197e-14]],

        [[ 5.8944e-12,  3.9831e-12,  3.3285e-12,  ...,  2.9484e-12,
           3.1694e-12,  4.3480e-12],
         [ 2.5972e-12,  1.7569e-12,  1.2548e-12,  ...,  1.1185e-12,
           1.3530e-12,  1.7021e-12],
         [ 8.6888e-13,  5.3019e-13,  3.4040e-13,  ...,  3.6830e-13,


------------------
None
112
---------------------after backward------------
tensor([[[-6.2762e-12, -4.2287e-12, -3.5105e-12,  ..., -3.0905e-12,
          -3.2800e-12, -4.4895e-12],
         [-2.5326e-12, -1.6954e-12, -1.1912e-12,  ..., -1.0814e-12,
          -1.2749e-12, -1.6047e-12],
         [-7.1479e-13, -4.1778e-13, -2.4361e-13,  ..., -3.0656e-13,
          -3.8520e-13, -3.5655e-13],
         ...,
         [ 2.3995e-15,  1.4892e-14, -1.3598e-13,  ...,  7.0560e-14,
           1.4403e-14,  1.3903e-13],
         [-1.8553e-14, -1.7879e-15, -1.7723e-13,  ...,  1.0740e-13,
          -8.1990e-15,  1.2276e-13],
         [-4.5235e-14,  2.6701e-14, -1.8660e-13,  ...,  1.4261e-13,
          -4.0485e-14,  8.1738e-14]],

        [[ 8.5530e-12,  5.8280e-12,  4.9260e-12,  ...,  4.3078e-12,
           4.6921e-12,  6.5198e-12],
         [ 4.1822e-12,  2.8739e-12,  2.1399e-12,  ...,  1.8176e-12,
           2.2335e-12,  2.8783e-12],
         [ 1.6633e-12,  1.0653e-12,  7.6492e-13,  ...,  7.1291e-13,


------------------
None
115
---------------------after backward------------
tensor([[[ 1.0649e-11,  7.1671e-12,  6.1526e-12,  ...,  5.4041e-12,
           5.7601e-12,  7.9618e-12],
         [ 4.5636e-12,  3.1016e-12,  2.2928e-12,  ...,  2.0173e-12,
           2.3926e-12,  3.0669e-12],
         [ 1.4566e-12,  9.1031e-13,  6.0192e-13,  ...,  6.4616e-13,
           8.0147e-13,  8.1285e-13],
         ...,
         [ 1.1594e-12,  2.3027e-13,  5.5680e-13,  ...,  4.1032e-13,
           8.5883e-13, -2.4324e-14],
         [ 9.9026e-13,  1.3591e-13,  4.6963e-13,  ...,  3.4705e-13,
           7.4931e-13, -3.4140e-14],
         [ 6.0867e-13,  1.9476e-14,  3.1227e-13,  ...,  1.7900e-13,
           4.3185e-13, -2.8779e-14]],

        [[-1.7027e-11, -1.1631e-11, -9.4101e-12,  ..., -8.3071e-12,
          -8.8679e-12, -1.2128e-11],
         [-6.8438e-12, -4.6140e-12, -3.1474e-12,  ..., -2.8957e-12,
          -3.4340e-12, -4.3350e-12],
         [-1.9260e-12, -1.1288e-12, -6.1539e-13,  ..., -8.0431e-13,


------------------
None
118
---------------------after backward------------
tensor([[[ 8.3353e-12,  5.6452e-12,  4.7286e-12,  ...,  4.1750e-12,
           4.4915e-12,  6.2061e-12],
         [ 3.7352e-12,  2.5403e-12,  1.8306e-12,  ...,  1.6114e-12,
           1.9509e-12,  2.4854e-12],
         [ 1.2927e-12,  8.0249e-13,  5.3007e-13,  ...,  5.5024e-13,
           7.1323e-13,  7.1341e-13],
         ...,
         [ 9.7454e-13,  1.7450e-13,  3.9351e-13,  ...,  3.5889e-13,
           7.5151e-13,  4.6322e-14],
         [ 8.4217e-13,  1.0001e-13,  3.1461e-13,  ...,  3.2070e-13,
           6.5366e-13,  3.9924e-14],
         [ 5.2479e-13,  1.5691e-14,  1.8548e-13,  ...,  1.9902e-13,
           3.7567e-13,  2.4643e-14]],

        [[-9.4010e-12, -6.3568e-12, -5.2690e-12,  ..., -4.5813e-12,
          -4.8031e-12, -6.7151e-12],
         [-3.8229e-12, -2.5751e-12, -1.8107e-12,  ..., -1.6091e-12,
          -1.8739e-12, -2.4254e-12],
         [-1.1018e-12, -6.5220e-13, -3.8377e-13,  ..., -4.6078e-13,


------------------
None
121
---------------------after backward------------
tensor([[[ 1.1461e-11,  7.7518e-12,  6.5515e-12,  ...,  5.7666e-12,
           6.2247e-12,  8.5658e-12],
         [ 5.1359e-12,  3.4975e-12,  2.5495e-12,  ...,  2.2307e-12,
           2.7117e-12,  3.4415e-12],
         [ 1.7760e-12,  1.1114e-12,  7.4117e-13,  ...,  7.6071e-13,
           9.8715e-13,  9.9139e-13],
         ...,
         [ 1.6060e-12,  2.9661e-13,  6.0435e-13,  ...,  5.9253e-13,
           1.2297e-12,  1.1833e-13],
         [ 1.3719e-12,  1.7017e-13,  4.6078e-13,  ...,  5.3657e-13,
           1.0665e-12,  1.0207e-13],
         [ 8.3593e-13,  4.4028e-14,  2.5383e-13,  ...,  3.4330e-13,
           6.0749e-13,  6.5551e-14]],

        [[ 6.9653e-12,  4.7393e-12,  4.0051e-12,  ...,  3.4824e-12,
           3.7997e-12,  5.2611e-12],
         [ 3.3872e-12,  2.3192e-12,  1.7245e-12,  ...,  1.4565e-12,
           1.8008e-12,  2.3007e-12],
         [ 1.3327e-12,  8.4581e-13,  6.0564e-13,  ...,  5.6281e-13,


7.0267493291758

In [ ]:
(gradgiven, gradpredict, epoch_loss) = pnet.ObtainGradientofDataNew(TrainingData=dataset, epochs=3, batch_size=4096)

In [ ]:
epochs = 1
for e in range(epochs):
    #print(epochs)
    loss = pnet.train(dataset=dataset, batch_size=4096)
    print(loss)

In [92]:
def CreateZeroTensor(TrainingData, batch_size):
    givenzeros = []
    predictzeros = []
    onebasket = []
    for batch in DataLoader(TrainingData, batch_size=batch_size, shuffle=True):
        given = batch['given'].to(torch.device('cuda:0'))
        predict = batch['predict'].to(torch.device('cuda:0'))
        dgiven = torch.zeros(given.shape).to(torch.device('cuda:0'))
        onestensor = torch.ones(given.shape)
        dpredict = torch.zeros(predict.shape)
        givenzeros.append(dgiven)
        predictzeros.append(dpredict)
        onebasket.append(onestensor)
    
    return (givenzeros, predictzeros, onebasket)

In [93]:
(givenzeros, predictzeros, onebasket) = CreateZeroTensor(TrainingData=dataset, batch_size=4096)


In [109]:
b = givenzeros
print(len(b))

122


In [110]:
b[0] = givenzeros[0] +1.2
b[1] = givenzeros[1] + 1.3
b


[tensor([[[1.2000, 1.2000, 1.2000,  ..., 1.2000, 1.2000, 1.2000],
          [1.2000, 1.2000, 1.2000,  ..., 1.2000, 1.2000, 1.2000],
          [1.2000, 1.2000, 1.2000,  ..., 1.2000, 1.2000, 1.2000],
          ...,
          [1.2000, 1.2000, 1.2000,  ..., 1.2000, 1.2000, 1.2000],
          [1.2000, 1.2000, 1.2000,  ..., 1.2000, 1.2000, 1.2000],
          [1.2000, 1.2000, 1.2000,  ..., 1.2000, 1.2000, 1.2000]],
 
         [[1.2000, 1.2000, 1.2000,  ..., 1.2000, 1.2000, 1.2000],
          [1.2000, 1.2000, 1.2000,  ..., 1.2000, 1.2000, 1.2000],
          [1.2000, 1.2000, 1.2000,  ..., 1.2000, 1.2000, 1.2000],
          ...,
          [1.2000, 1.2000, 1.2000,  ..., 1.2000, 1.2000, 1.2000],
          [1.2000, 1.2000, 1.2000,  ..., 1.2000, 1.2000, 1.2000],
          [1.2000, 1.2000, 1.2000,  ..., 1.2000, 1.2000, 1.2000]],
 
         [[1.2000, 1.2000, 1.2000,  ..., 1.2000, 1.2000, 1.2000],
          [1.2000, 1.2000, 1.2000,  ..., 1.2000, 1.2000, 1.2000],
          [1.2000, 1.2000, 1.2000,  ...,

In [96]:
a = givenzeros

In [97]:
a = 

[tensor([[[0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          ...,
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.]],
 
         [[0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          ...,
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.]],
 
         [[0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          ...,
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.]],
 
         ...,
 
         [[0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          ...,
          [0., 0., 0.,  ..., 0., 

In [5]:
encoder = model.Encoder(n_inputs=13, n_hiddens=64).to(torch.device('cuda:0'))
decoder = model.AttentionDecoder(n_hiddens=64, n_features=13).to(torch.device('cuda:0'))

In [14]:
def ObtainGradientOfWeightInModelNew(ModelEnc, ModelDec, TrainingData, batch_size, MaxGrad=100.0):
        enc = copy.deepcopy(ModelEnc)
        dec = copy.deepcopy(ModelDec)
        enc.zero_grad()
        dec.zero_grad()
        epoch_loss = 0

        for batch in DataLoader(TrainingData, batch_size=batch_size, shuffle=True):
            (loss, given, predict) = GetLossFunc(batch, enc, dec)
            loss.backward()
            epoch_loss += loss.item()
    
        for w in enc.parameters():
          #  print('----------------------wgrad----------------------')
          #  print(w.grad)
            if torch.max(torch.abs(w.grad))>MaxGrad:
                w.grad = w.grad/torch.max(torch.abs(w.grad))*MaxGrad
               # print('------------------wgradupdate-------------------')
               # print(w.grad)
    
        for w in dec.parameters():
            if torch.max(torch.abs(w.grad))>MaxGrad:
                w.grad = w.grad/torch.max(torch.abs(w.grad))*MaxGrad
    
        return (epoch_loss, enc, dec)

In [15]:
(epoch_loss, enc, dec) = ObtainGradientOfWeightInModelNew(encoder, decoder, TrainingData=dataset,batch_size=4096 )

In [64]:
def GetLossFunc(batch, enc, dec, autograd=True):
    if autograd:
        given = batch['given'].to(torch.device('cuda:0'))
        predict = batch['predict'].to(torch.device('cuda:0'))
        answer = batch['answer'].to(torch.device('cuda:0')) 
        given1 = given.clone().detach().requires_grad_(True)
        predict1 = predict.clone().detach().requires_grad_(True)
        encoder_outs, context = enc(given1)
        guess = dec(encoder_outs, context, predict1)
        mse_loss = nn.MSELoss()
        loss = mse_loss(guess, answer)
    else:
        given1 = batch['given'].to(torch.device('cuda:0'))
        predict1 = batch['predict'].to(torch.device('cuda:0'))
        answer = batch['answer'].to(torch.device('cuda:0')) 
        encoder_outs, context = enc(given1)
        guess = dec(encoder_outs, context, predict1)
        mse_loss = nn.MSELoss()
        loss = mse_loss(guess, answer)
        
    return (loss,given1, predict1 )


In [71]:
from torch import nn 

def GetGradientUsingAutoGrad(enc, dec, TrainingData,batch_size):
    givenbag = []
    predictbag = []
    for batch in DataLoader(TrainingData, batch_size=batch_size, shuffle=True):
        (loss, given1, predict1) = GetLossFunc(batch, enc, dec, autograd=True)
        grad = torch.autograd.grad(outputs=loss, inputs=(given1,predict1), retain_graph=True, allow_unused=True)
        loss.backward()
        givenbag.append(given1.grad)
        predictbag.append(predict1.grad)
    return (grad,enc, dec, givenbag, predictbag)

In [72]:
( grad,enc, dec, givenbag, predictbag) = GetGradientUsingAutoGrad(enc, dec, TrainingData=dataset, batch_size=4096)

In [75]:
predictbag

[tensor([[[ 2.0332e-09,  3.2858e-09, -1.1388e-09,  ..., -4.4638e-09,
           -6.9855e-09, -3.2229e-09],
          [ 2.1751e-09,  7.2334e-09,  1.0810e-09,  ..., -5.4148e-09,
           -8.8567e-09, -5.2784e-09],
          [ 1.4096e-09,  1.0710e-08,  5.8685e-09,  ..., -5.4800e-09,
           -1.1504e-08, -8.4519e-09],
          ...,
          [-2.0426e-08, -7.3111e-08,  1.2361e-07,  ...,  5.2124e-08,
            4.8282e-08,  6.9255e-08],
          [-4.0366e-08, -1.6153e-07,  2.2103e-07,  ...,  8.5868e-08,
            1.6357e-07,  2.2350e-07],
          [-2.1718e-07, -2.5224e-07,  3.6683e-07,  ..., -2.8988e-08,
            3.6659e-07,  5.9498e-07]],
 
         [[ 2.5458e-09,  2.2677e-09, -1.1733e-09,  ..., -3.9874e-09,
           -6.7951e-09, -2.7916e-09],
          [ 3.2655e-09,  4.1472e-09,  1.4556e-10,  ..., -3.9036e-09,
           -8.9973e-09, -3.7405e-09],
          [ 3.2524e-09,  4.8330e-09,  3.7693e-09,  ..., -2.5923e-09,
           -1.2111e-08, -5.5215e-09],
          ...,
    

In [ ]:
onebasket

In [77]:
testbasket = []
for i in range(len(givenzeros)):
    testbasket.append((givenzeros[i]-onebasket[i])/4)
    print(testbasket[i].shape)

NameError: name 'givenzeros' is not defined

In [ ]:
testbasket

In [ ]:
if torch.abs(testbasket[0]) > 100:
    print('yes')
else:
    print('no')

In [78]:
finaldatagrad = []
for i in range(len(testbasket)):
    if torch.max(torch.abs(testbasket[i])) > 0.2:
        testbasket[i] = testbasket[i]/torch.max(torch.abs(testbasket[i]))*0.2

In [79]:
len(testbasket)

0

In [80]:
testbasket

[]

In [81]:
for i in testbasket:
    if torch.max(torch.abs(i)) > 0.2:
        i = i/torch.max(torch.abs(i))*0.2
        print(i.shape)


i

NameError: name 'i' is not defined

In [ ]:
dxp

In [ ]:
len(testbasket)

In [ ]:
givenzeros[0].shape

In [12]:
def GetLossFunc(batch, enc, dec):
        given = batch['given'].to(torch.device('cuda:0'))
        predict = batch['predict'].to(torch.device('cuda:0'))
        answer = batch['answer'].to(torch.device('cuda:0')) 
        encoder_outs, context = enc(given)
        guess = dec(encoder_outs, context, predict)
        mse_loss = nn.MSELoss()
        loss = mse_loss(guess, answer)

        return (loss, given, predict)

In [13]:
import copy
def ObtainListOfParameters(Model):
        l=list()
        for w in Model.parameters():
            l.append(copy.deepcopy(w))
        return l
    
def UpdateModel(Model, Alpha,MaxGrad=1,ListOfParam=None):
    if ListOfParam is None:
        for w in Model.parameters():
            w.data=w.data + Alpha* w.grad
    else:
        i=0
        for w in Model.parameters():
            w.data=w.data +Alpha * ListOfParam[i].grad
            i=i+1

In [ ]:
l=list()
for w in enc.parameters():
    #print(w.grad)
    l.append(w)
    #l.append(copy.deepcopy(w))

In [ ]:
print(l[1].grad)

In [ ]:
enc

In [ ]:
w = ObtainListOfParameters(encoder)
print(w[0].shape)

In [ ]:
w1 = ObtainListOfParameters(encoder)
print(w1[1].grad)

In [ ]:
len(w1)

In [ ]:
for j in range(len)

In [ ]:
import torch
a = torch.rand(10, requires_grad=True)
b = torch.rand(10, requires_grad=True)

output = (2 * a).sum()

gradient = torch.autograd.grad(output, a, retain_graph=True)
print(gradient)
output.backward()


In [ ]:
grad = a.grad
print(grad)

In [ ]:
import torch
net = torch.nn.Linear(2, 2)
d = net.state_dict()
d.update({"custom_stuff": 123})
torch.save(d, "net.pth")

# Load it from the serialized file

new_net = torch.nn.Linear(2, 2)
# By default, strict=True, then you need to force it to False to not raise an error
state_dict = torch.load("net.pth")
custom_stuff = state_dict["custom_stuff"] # Retrieving your stuff after loading
new_net.load_state_dict(state_dict, strict=False) 
# NOTE: you can just del state_dict["custom_stuff"] if you want, then strict can be set True

# Check that the parameters have been loaded as expected

print(net.weight.data.equal(new_net.weight.data))
print(net.bias.data.equal(new_net.bias.data))

In [ ]:
tensor = [grad, gradient]

In [ ]:
tensor

In [ ]:
len(tensor)


In [111]:
def attack_feature(sensorID,num):
    l=list()
    for i in range(0,51*num,51):
        if sensorID==0:
            for j in range(0,5):
                l.append(i+j)
        if sensorID==1:
            for j in range(5,16):
                l.append(i+j)
        if sensorID==2:
            for j in range(16,25):
                l.append(i+j)
        if sensorID==3:
            for j in range(25,34):
                l.append(i+j)
        if sensorID==4:
            for j in range(34,47):
                l.append(i+j)
        if sensorID==5:
            for j in range(47,51):
                l.append(i+j)
    return l

In [114]:
li_attack=attack_feature(3,4)
li_attack

[25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 178,
 179,
 180,
 181,
 182,
 183,
 184,
 185,
 186]